### ISSUE TITLE
nzb-notify problem with nzbget module

### ISSUE THREAD

**Issue by elmero1** [caronc/nzb-notify#53] opened 2019-03-19 16:57 UTC
My setup doesn't work anymore. I use the actual nzb-notify (master branch) and nzbget as a docker conatiner (linuxserver/nzbget).

In nzbget I get an PP-Failure:
> Mon Mar 18 2019 22:54:15	INFO	Executing post-process-script nzb-notify/Notify.py for movie-file
> Mon Mar 18 2019 22:54:15	INFO	Notify: Traceback (most recent call last):
> Mon Mar 18 2019 22:54:15	INFO	Notify: File "/downloads/scripts/nzb-notify/Notify.py", line 159, in 
> Mon Mar 18 2019 22:54:15	INFO	Notify: from nzbget import SCRIPT_MODE
> Mon Mar 18 2019 22:54:15	INFO	Notify: ImportError: No module named nzbget
> Mon Mar 18 2019 22:54:15	ERROR	Post-process-script nzb-notify/Notify.py for movie-file failed (terminated with unknown status)

Until last week, everything worked fine. In another community I received the hint to install the two missing modules (inside the docker container):
pip install nzbget
pip install apprise

Is this the solution? Why is this necessary now?

**Comment by caronc** [comment] 2019-03-19 17:12
Yeah, i updated the main page a while ago:
```bash
# Pull in dependencies:
pip install -i requirements.txt
```

The problem is when i develop against [apprise](https://github.com/caronc/apprise) and [pynzbget](https://github.com/caronc/pynzbget) independently (_each with their own git repositories_), i have to come back to here and add them manually to this package (, [Subliminal](https://github.com/caronc/nzb-subliminal), [Tidyit](https://github.com/caronc/nzbget-tidyit), and [Dirwatch](https://github.com/caronc/nzbget-dirwatch)).  It just doesn't make sense to not reference them how they were meant to be (and that's via a single install of it on your vm/container/system) :slightly_smiling_face:

The other issue was with SSL... Both Notify, and Subliminal plugins require SSL to communicate with secure websites. The big problem was that the SSL package i packaged with these 2 plugins was badly incompatible with the newer versions. However, if i included the newer version of it, it was badly incompatible with older systems.   Again.. same thing; it should just be a global package separately maintained.

This is how it will be going forward unfortunately; it's for the best.

**Comment by elmero1** [comment] 2019-03-19 17:32
Thanks for your help caronc! 
Do you have experience with the linuxserver/nzbget container? How can I execute the command in the container? Is there a possibility with docker-compose and use further the official container from docker hub?

**Comment by caronc** [comment] 2019-03-19 17:54
I'm not too familiar with that container (i don't maintain it or know the person who does).

It looks like it has you specify `-v <path to data>:/config` in the configuration ([source](https://hub.docker.com/r/linuxserver/nzbget/)). I presume you're providing the nzb-notify plugin then? Or does the docker image ship with it? 

You could try opening up the _docker-compose.yml_ file and possibly add a line like:
```
  nzbget:
    ...
    ...
    command: >
      bash -c '
      cd /path/to/pynzbget/ && pip install -i requirements.txt
      '
```
(_no promises though as i'm not very educated with docker_ :slightly_smiling_face: )

If it ships with the docker image originally, then it should be fixed there too.

**Comment by caronc** [comment] 2019-03-27 16:14
I'm going to close this ticket off now if you don't mind? I presume you got it all figured out?

**Comment by elmero1** [comment] 2019-03-27 16:48
Yes you can close the ticket. I have installed the pip modules and everything work fine. Thanks for your help.

**Closed** 2019-03-27 16:55 UTC
Labels: question

**Comment by MoeJoe87** [comment] 2019-06-05 23:42
@elmero1 How did you install the pip modules inside the Docker container?

**Comment by elmero1** [comment] 2019-06-06 05:36
@MoeJoe87 
With my own dockerfile:
`
FROM linuxserver/nzbget
MAINTAINER .

# install packages
RUN \
 apk add --no-cache \
        py-pip

COPY /data/scripts/nzb-notify/requirements.txt /

# pip modules install
RUN \
 pip install -r requirements.txt
`

**Comment by pfckiko** [comment] 2020-03-29 04:46
If you're using Unraid you need to use the console one the Sabnbzd docker then follow this tutorial 

To install pip, securely 1 download get-pip.py by following this link: get-pip.py. Alternatively, use curl:

> curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py


Then run the following command in the folder where you have downloaded get-pip.py:

> python get-pip.py


then you run this common 

> pip install -r requirements.txt

**Comment by pfckiko** [comment] 2020-03-29 04:48
> @elmero1 How did you install the pip modules inside the Docker container?

If you're using Unraid you need to use the console one the Sabnbzd docker then follow this tutorial

To install pip, securely 1 download get-pip.py by following this link: get-pip.py. Alternatively, use curl:

curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py

Then run the following command in the folder where you have downloaded get-pip.py:

python get-pip.py

then you run this common

pip install -r requirements.txt

**Comment by strongy** [comment] 2020-07-13 13:29
> > @elmero1 How did you install the pip modules inside the Docker container?
> 
> If you're using Unraid you need to use the console one the Sabnbzd docker then follow this tutorial
> 
> To install pip, securely 1 download get-pip.py by following this link: get-pip.py. Alternatively, use curl:
> 
> > curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
> 
> Then run the following command in the folder where you have downloaded get-pip.py:
> 
> > python get-pip.py
> 
> then you run this common
> 
> > pip install -r requirements.txt

this will get wiped the momment theirs an update though wont it
